import { env } from "cloudflare:workers";
import { hashPassword } from "../password";

const owner=(request:Request)=>request.headers.get("oai-authenticated-user-id")||"farmacias-abc";

export async function GET(request:Request){try{const result=await env.DB.prepare("SELECT id,name,email,role,status,CASE WHEN password_hash IS NOT NULL THEN 1 ELSE 0 END AS hasPassword,created_at AS createdAt FROM app_users WHERE owner_id=? ORDER BY name").bind(owner(request)).all();return Response.json(result.results)}catch(error){console.error("users GET failed",error);return Response.json({error:"No fue posible cargar los usuarios."},{status:503})}}

export async function POST(request:Request){try{const body=await request.json() as Record<string,unknown>,name=String(body.name||"").trim(),email=String(body.email||"").trim().toLowerCase(),password=String(body.password||""),role=String(body.role||"Empleado"),status=String(body.status||"Activo");if(!name||!/^\S+@\S+\.\S+$/.test(email)||password.length<6||!["Administrador","Empleado"].includes(role)||!["Activo","Inactivo"].includes(status))return Response.json({error:"Revisa el nombre, correo, contraseña (mínimo 6 caracteres), rol y estado."},{status:400});const credentials=await hashPassword(password);await env.DB.prepare("INSERT INTO app_users(owner_id,name,email,role,status,password_salt,password_hash,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(owner(request),name,email,role,status,credentials.salt,credentials.hash,new Date().toISOString()).run();return Response.json({ok:true})}catch(error){console.error("users POST failed",error);const message=String(error).includes("UNIQUE")?"Ese correo ya está registrado.":"No fue posible guardar el usuario.";return Response.json({error:message},{status:503})}}

export async function PATCH(request:Request){try{const body=await request.json() as Record<string,unknown>,id=Number(body.id),status=String(body.status||""),password=String(body.password||"");if(!Number.isInteger(id))return Response.json({error:"Usuario inválido."},{status:400});if(password){if(password.length<6)return Response.json({error:"La contraseña debe tener al menos 6 caracteres."},{status:400});const credentials=await hashPassword(password);await env.DB.prepare("UPDATE app_users SET password_salt=?,password_hash=? WHERE id=? AND owner_id=?").bind(credentials.salt,credentials.hash,id,owner(request)).run();return Response.json({ok:true})}if(!["Activo","Inactivo"].includes(status))return Response.json({error:"Estado inválido."},{status:400});await env.DB.prepare("UPDATE app_users SET status=? WHERE id=? AND owner_id=?").bind(status,id,owner(request)).run();return Response.json({ok:true})}catch(error){console.error("users PATCH failed",error);return Response.json({error:"No fue posible actualizar el usuario."},{status:503})}}

export async function DELETE(request:Request){try{const id=Number(new URL(request.url).searchParams.get("id"));if(!Number.isInteger(id))return Response.json({error:"Usuario inválido."},{status:400});await env.DB.prepare("DELETE FROM app_users WHERE id=? AND owner_id=?").bind(id,owner(request)).run();return Response.json({ok:true})}catch(error){console.error("users DELETE failed",error);return Response.json({error:"No fue posible eliminar el usuario."},{status:503})}}
